# Generated by Django 3.2.3 on 2021-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerbyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registered', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
                ('generated', models.DateTimeField(blank=True, null=True)),
                ('toot', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
