# Generated by Django 3.2.3 on 2021-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_derbyname_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derbyname',
            name='toot',
        ),
        migrations.AddField(
            model_name='derbyname',
            name='tooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
