# Generated by Django 3.2.3 on 2021-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0004_auto_20210527_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='derbyname',
            name='toot_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
