# Generated by Django 3.2.4 on 2021-06-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0005_derbyname_toot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='derbyname',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
