# Generated by Django 3.2.4 on 2021-06-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0007_colorscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='derbyname',
            name='bg_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jersey_bg', to='names.colorscheme'),
        ),
        migrations.AddField(
            model_name='derbyname',
            name='fg_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jersey_fg', to='names.colorscheme'),
        ),
        migrations.AddField(
            model_name='derbyname',
            name='jersey',
            field=models.ImageField(blank=True, null=True, upload_to='jerseys/'),
        ),
    ]
