# Generated by Django 3.2.4 on 2021-06-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0008_auto_20210609_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derbyname',
            name='bg_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jersey_bg', to='names.colorscheme'),
        ),
        migrations.AlterField(
            model_name='derbyname',
            name='fg_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jersey_fg', to='names.colorscheme'),
        ),
    ]
